name: Build & Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/fastzakat-web
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Build the Docker image with multiple tags
      run: |
        docker build . \
          -t ghcr.io/${{ github.repository_owner }}/fastzakat-web:${{ github.ref_name }} \
          -t ghcr.io/${{ github.repository_owner }}/fastzakat-web:latest \
          -t ghcr.io/${{ github.repository_owner }}/fastzakat-web:${{ github.sha }} \
          --build-arg VITE_API_URL=${{ vars.FAST_ZAKAT_API_URL }}
    - name: Push the Docker Images
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/fastzakat-web:${{ github.ref_name }}
        docker push ghcr.io/${{ github.repository_owner }}/fastzakat-web:latest
        docker push ghcr.io/${{ github.repository_owner }}/fastzakat-web:${{ github.sha }}
